# Generated by Django 3.2.6 on 2021-08-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='magneta_model',
            field=models.CharField(default='bach', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
