# Generated by Django 3.2.6 on 2021-08-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210822_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackcodes',
            name='code1',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='trackcodes',
            name='code2',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='duel_code',
            field=models.CharField(default='', max_length=6, null=True),
        ),
    ]
