# Generated by Django 3.2.6 on 2021-08-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210822_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='duel_code',
            field=models.CharField(blank=True, default='', max_length=6, null=True),
        ),
    ]
